version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    volumes:
      - .:/data
    ports:
      - '80:80'
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
  db:
    driver: local
